### ISSUE TITLE
Measurement errors 

### ISSUE THREAD

**Issue by YaBr11** [pimoroni/pmw3901-python#7]
I'm experiencing weird measurement errors with the PMW3901 sensor.
The sensor value is requested at a fixed rate.
When measuring with 30 Hz rate, this is the output of the sensor calibrated to m/s:
![30Hz_freq](https://user-images.githubusercontent.com/62811499/97157389-51c03f00-1778-11eb-8479-380008c97ad2.png)
From time to time it looks like there is an high-frequent oscillation overlayed.
But measuring with 110 Hz shows very frequent outliers at the exact double value of the last correct measurement:
![110Hz_freq](https://user-images.githubusercontent.com/62811499/97157419-5a187a00-1778-11eb-8f6d-4740df7069a9.png)

FFT over several frequencies shows that the noise/sensor malfunction has a frequency of 121 Hz, which happens to be exactly the frame rate of the sensor.

It looks to me like the sensor measures internally at 121 Hz and then just adds up all the values until the value is read by the python library. So if the read frequency doesn't match the internal frequency, the measurement value sometimes contains more and some times less measurements added up.
Anybody else experiencing this issue?

I'm using the library in ROS, but I think this problem is not ROS-related. Is it maybe a timing issue? The read frequency is not 100% constant in ROS but probably neither in python itself.

Any clues how to solve this?

**Comment by Gadgetoid** [comment]
I would venture that there's a mistake in your conversion from the relative position read out by the sensor into velocity.

Any one sensor reading produces only a relative position- so the values indicate the distance travelled since the last reading. If the readings cannot be guaranteed at a constant rate then you would have to keep track of position over time and compute the velocity from that.

That said- this sensor has a particularly onerous datasheet full of "write these 50 register values of proprietary magic" and a particularly contrived process for changing the output data rate. It would not surprise me if I had got something wrong here... but a cursory check doesn't reveal anything I've overlooked in the burst data read.

**Comment by YaBr11** [comment]
Thanks for your help. I more or less solved the issue.
You were on the right on the right track, but the problem wasn't an inconstant reading rate. 

The problem disappears when reading the the sensor value at 30.25 Hz instead of 30 Hz, because that's 121 Hz /4.
When I'm not matching the framerate of the sensor or factors of it, I have once in a while 5 sensor measurements added up instead of 4 in the output, which causes the spikes in my graphs.

What surprises me is that no one else experienced this issue, because in my opinion the same problem should occur in the example code, if you're not lucky enough to hit exactly a read frequency of 121/N Hz.
